### ISSUE TITLE
a lot of empty sub-compartment regions

### ISSUE THREAD

**Issue by Nuturetree** [CSOgroup/CALDER2.0#3]
Respected Author
Hi
  Thank you very much for developing CALDER 2.0, a very useful tool !  When I used it I encountered a problem that the region of sub-compartment can not complete coverage of the genome regions and I feel these empty regions have lot. I also encountered this problem when I ran test data.
   I look forward to hearing from you.
Best
Nutures
![Snipaste_2022-08-31_12-02-44](https://user-images.githubusercontent.com/26841049/187590026-7d313e73-d1e3-4784-ae02-d65face18907.png)

**Comment by YuanlongLiu** [comment]
Hi, what do you mean by empty regions? I can see a gap for example between 1-20000 and 40001-380000.  
This is not surprising because Calder will remove regions where contacts are too sparse. What is the total length of empty regions you get? Can you visualise how the Hi-C map looks like at these regions?

**Comment by Nuturetree** [comment]
Thank you for your reply, I understood it.
